animals_app/urls.py
from django.urls import path

from .views import (view_animals, view_detail_animal, add_animal_view,
                    delete_animal_view, edit_animal_view,
                    change_animal_status, filtered_animals_view)


app_name = "animals"

urlpatterns = [
    path('', view_animals, name='index'),
    path('detail_animal/<int:animal_id>/',
         view_detail_animal, name='detail_animal'),
    path('add_animal/', add_animal_view, name='add_animal'),
    path('edit_animal/<int:animal_id>/', edit_animal_view, name='edit_animal'),
    path('delete_animal/<int:animal_id>/',
         delete_animal_view, name='delete_animal'),
    path('change-animal-status/<int:animal_id>/',
         change_animal_status, name='change_animal_status'),
    path('filtered_animals/', filtered_animals_view, name='filtered_animals'),
]

comments_app/urls.py
from django.urls import path
from .views import (add_comment_view, edit_comment_view,
                    delete_comment_view, change_comment_status)


app_name = "comments"

urlpatterns = [
    path('add_comment/<int:animal_id>', add_comment_view, name='add_comment'),
    path('edit_comment/<int:comment_id>/<int:animal_id>/',
         edit_comment_view, name='edit_comment'),
    path('delete/<int:comment_id>/<int:animal_id>/',
         delete_comment_view, name='delete_comment'),
    path('change-comment-status/<int:comment_id>/',
         change_comment_status, name='change_comment_status'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animals_app.urls', namespace='animals')),
    path('', include('comments_app.urls', namespace='comments')),
    path('', include('users.urls', namespace='users')),
    path('', include('substack_app.urls', namespace='substack')),
    path('', include('clinics_app.urls', namespace='clinics')),
    path('', include('groups_app.urls', namespace='groups')),
    path('api/', include('animals_api.urls', namespace='animals_api')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/animals/add_animal.html
{% extends 'base.html' %}
{% load static %}
{% block lists %}
  Подать объявление
{% endblock %}

{% block content %}
<div>
  <div class="container" >
    <form method="post" enctype="multipart/form-data" class="mb-5">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="col-md-6"><input required class="form-label" name="images" type="file" multiple></div>
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
  </div>
</div>
{% endblock %}

templates/animals/delete_animal.html
{% extends 'base.html' %}
{% load static %}
{% block lists %}
  Главная страница
{% endblock %}

{% block content %}
<h2>Вы уверены, что хотите удалить объявление?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <button type="submit">Отмена</button>
</form>
{% endblock %}

templates/animals/detail_animals.html
{% extends 'base.html' %}
{% load static %}
{% block lists %}
  Главная страница
{% endblock %}

{% block content %}
<div class="border border-success p-3 mb-1">
  <h5>{% for target in animal.target.all %} {{ target.name }}
      {% endfor %}
  </h5>
      <h5>Вид животного:
        {% for kind in kinds %} {{ kind }} {% if not forloop.last %}, {% endif %}
        {% endfor %}
      </h5>
      <h5>Кличка: {{ animal.nickname }}</h5>
      <h5>Описание: {{ animal.description }}</h5>
      <h5>Приметы: {{ animal.signs }}</h5>
      <h5>Город: {{ animal.city }}</h5>
      <h5>Номер телефона: {{ animal.phone_number }}</h5>
      <h5>Контактное лицо: {{ animal.contact_people }}</h5>
      
      <div class="container" style="height: 50%; width: 50%">
        <div id="carouselExampleFade{{ animal.id }}"  class="carousel slide carousel-fade" data-bs-ride="carousel">
          <div class="carousel-inner">
            {% for image in animal.images.all %}
            <div class="carousel-item active mt-3">
              <img src="{{ image.images.url }}" class="d-block w-100" alt="...">
            </div>
            {% endfor %}
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade{{ animal.id }}"  data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Предыдущий</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade{{ animal.id }}"  data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Следующий</span>
          </button>
        </div>
      </div>
      
      {% if user.is_authenticated and user == animal.submit %}
      <div class="btn-group mt-2" role="group">
        <a href="{% url 'animals:delete_animal' animal.id %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'animals:edit_animal' animal.id %}" class="btn btn-warning">Изменить</a>
      </div>
</div>
      {% endif %}
      
  <div class="card mt-4 mb-4">
    <div class="card-header" style="background-color:#e3f2fd;">
      <b>Комментарии</b>
    </div>
    {% for comment in comments %}
    <div class="card-body">
      <div class="d-flex justify-content-between border-top">
        <div>
          <h5 class="card-target">{{comment}}</h5>
        </div>
        {% if user.is_authenticated and user == comment.author %}
        <div class="btn-group mt-2" style="height:40px" role="group">
          <button class="btn btn-danger" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Удалить</button>
          <a href="{% url 'comments:edit_comment' comment.id animal.id %}" class="btn btn-warning">Изменить</a>
        </div>
        {% endif %}
      </div>
      <p class="card-text">{{ comment.text }}</p>
    </div>
    
    <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1"><div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-target fs-5" id="exampleModalToggleLabel"></h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Удалить комментарий?
        </div>
        <div class="modal-footer">
          <a href="{% url 'comments:delete_comment' comment.id animal.id %}" class="btn btn-danger">Удалить</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  
  <div class="container mt-2 mb-2" style="width: 75%">
    <form method="POST" action="{% url 'comments:add_comment' animal.id %}">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
  </div>
</div>
</div>
{% endblock %}

templates/animals/filtered_animals.html
{% extends 'base.html' %}
{% load static %}
{% block lists %}
  Страница фильтрации
{% endblock %}

{% block content %}
{% if animals %}
  <div class="d-flex justify-content-start">

      <div class="mb-5 text-center">
        <form method="get" action="{% url 'animals:filtered_animals' %}" class="row g-3 needs-validation" novalidate>
          <div class="col-md-4">
            <label for="animal_target" class="form-label"><b>Цель объявления</b></label>
            <input type="text" class="form-control" id="animal_target" name="target" value="{{ request.GET.target }}">
          </div>
          <div class="col-md-4">
            <label for="kind" class="form-label"><b>Вид животного</b></label>
            <input type="text" class="form-control" id="kind" name="kind" value="{{ request.GET.kind }}">
          </div>
          <div class="col-md-1 align-self-end">
            <button class="btn btn-primary" type="submit">Показать</button>
          </div>
        </form>
      </div>
    </div>


    <div class="row">
      {% for animal in animals %}
      <div class="col-12 col-md-6 col-lg-3 mb-4 d-flex">
          <div class="card border-dark" style="width: 18rem"; style="background-color:#e3f2fd;">
            <div id="carouselExampleFade{{ animal.id }}"  class="carousel slide carousel-fade" data-bs-ride="carousel">
                <div class="carousel-inner">
                  {% for image in animal.images.all %}
                  <div class="carousel-item active" style="height: 195px;">
                    <img src="{{ image.images.url }}" class="d-block w-100" alt="...">
                  </div>
                  {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade{{ animal.id }}"  data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Предыдущий</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade{{ animal.id }}"  data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Следующий</span>
                </button>
              </div>
          
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                {% for target in animal.target.all %}
                <h5 class="card-title">{{ target.name }}</h5>
                {% endfor %}
                {% if user.is_authenticated %}
                <button type="button" class="btn-substack btn border-0 text-primary" data-animal-id="{{ animal.id }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" class="bi bi-substack" viewBox="0 0 16 16">
                      <path d="M15 3.604H1v1.891h14v-1.89ZM1 7.208V16l7-3.926L15 16V7.208H1ZM15 0H1v1.89h14V0Z"/>
                    </svg>
                  </button> 
                {% endif %}    
              </div>
              <p class="card-text"><b>Вид животного:</b> 
              {% for kind in animal.kind.all %}
              {{ kind.name }}
              {% endfor %}</p>
              <p class="card-text"><b>Описание:</b> {{ animal.description }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <a href="{% url 'animals:detail_animal' animal.id %}" class="btn btn-primary">Посмотреть</a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
</div>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if animals.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ animals.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo;</span>
        </li>
      {% endif %}
      {% for page_num in animals.paginator.page_range %}
        {% if animals.number == page_num %}
          <li class="page-item active">
            <span class="page-link">{{ page_num }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if animals.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ animals.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
  
{% else %}
<div class="text-left">
  <h4>Не найдено по следующему запросу поиска: 
    <ul>
      <li>Цель объявления: {{ request.GET.target }} </li>
      <li>Вид животного: {{ request.GET.kind }}</li>
    </ul>
  </h4>
</div>
{% endif %}
{% endblock %}

templates/animals/index.html
{% extends 'base.html' %}
{% load static %}
{% block lists %}
  Главная страница
{% endblock %}

{% block content %}
{% if animals %}
<div class="d-flex justify-content-start">
  <div class="mb-5 text-center">
    <form method="get" action="{% url 'animals:filtered_animals' %}" class="row g-3 needs-validation" novalidate>
      <div class="col-md-4">
        <label for="animal_target" class="form-label"><b>Цель объявления</b></label>
        <input type="text" class="form-control" id="animal_target" name="target" value="{{ request.GET.target }}">
      </div>
      <div class="col-md-4">
        <label for="kind" class="form-label"><b>Вид животного</b></label>
        <input type="text" class="form-control" id="kind" name="kind" value="{{ request.GET.kind }}">
      </div>
      <div class="col-md-1 align-self-end">
        <button class="btn btn-primary" type="submit">Показать</button>
      </div>
    </form>
  </div>
</div>

<div class="row">
  {% for animal in animals %}
  <div class="col-12 col-md-6 col-lg-3 mb-4 d-flex">
    <div class="card border-dark" style="width: 18rem"; style="background-color:#e3f2fd;">
      <div id="carouselExampleFade{{ animal.id }}" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner">
          {% for image in animal.images.all %}
          <div class="carousel-item active" style="height: 195px;">
            <img src="{{ image.images.url }}" class="d-block w-100" alt="...">
          </div>
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade{{ animal.id }}"  data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Предыдущий</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade{{ animal.id }}"  data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Следующий</span>
        </button>
      </div> 
      
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
          {% for target in animal.target.all %}
          <h5 class="card-title">{{ target.name }}</h5>
          {% endfor %}
          <button type="button" class="btn-substack btn border-0 text-primary" data-animal-id="{{ animal.id }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" class="bi bi-substack" viewBox="0 0 16 16">
              <path d="M15 3.604H1v1.891h14v-1.89ZM1 7.208V16l7-3.926L15 16V7.208H1ZM15 0H1v1.89h14V0Z"/>
            </svg>
          </button>              
        </div>
        <p class="card-text"><b>Вид животного:</b> {% for kind in animal.kind.all %}
          {{ kind.name }}
          {% endfor %}
        </p>
        <p class="card-text"><b>Описание:</b> {{ animal.description }}</p>
        <a href="{% url 'animals:detail_animal' animal.id %}" class="btn btn-primary">Посмотреть</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if animals.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ animals.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo;</span>
    </li>
    {% endif %}
    {% for page_num in animals.paginator.page_range %}
    {% if animals.number == page_num %}
    <li class="page-item active">
      <span class="page-link">{{ page_num }}</span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if animals.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ animals.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% else %}
<div class="text-center">
  <h1>Объявлений нет</h1>
</div>
{% endif %}

{% endblock %}