animals_app/urls.py
from django.urls import path

from .views import (view_animals, view_detail_animal, add_animal_view,
                    delete_animal_view, edit_animal_view,
                    change_animal_status, filtered_animals_view)


app_name = "animals"

urlpatterns = [
    path('', view_animals, name='index'),
    path('detail_animal/<int:animal_id>/',
         view_detail_animal, name='detail_animal'),
    path('add_animal/', add_animal_view, name='add_animal'),
    path('edit_animal/<int:animal_id>/', edit_animal_view, name='edit_animal'),
    path('delete_animal/<int:animal_id>/',
         delete_animal_view, name='delete_animal'),
    path('change-animal-status/<int:animal_id>/',
         change_animal_status, name='change_animal_status'),
    path('filtered_animals/', filtered_animals_view, name='filtered_animals'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animals_app.urls', namespace='animals')),
    path('', include('comments_app.urls', namespace='comments')),
    path('', include('users.urls', namespace='users')),
    path('', include('substack_app.urls', namespace='substack')),
    path('', include('clinics_app.urls', namespace='clinics')),
    path('', include('groups_app.urls', namespace='groups')),
    path('api/', include('animals_api.urls', namespace='animals_api')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import (login_view, logout_view, register_user_view,
                    view_admin_dashboard, view_profile,
                    edit_profile_view, CustomPasswordChangeView)

app_name = "users"

urlpatterns = [
    path('profile/', view_profile, name='profile'),
    path('admin_dashboard/', view_admin_dashboard, name='admin_dashboard'),
    path('registration', register_user_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('edit_profile/', edit_profile_view, name='edit_profile'),
    path('change_password/', CustomPasswordChangeView.as_view(),
         name='change_password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    phone_number = PhoneNumberField(
        'Номер телефона',
        unique=True,
    )
    father_name = models.CharField(
        'Отчество',
        max_length=50,
        blank=True,
        null=True
    )
    image = models.ImageField(
        'Фотография',
        upload_to='users/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    PasswordChangeForm
    )
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'father_name',
                  'email', 'phone_number', 'image', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class':
                                                       'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['father_name'].widget.attrs.update({'class':
                                                        'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone_number'].widget.attrs.update({'class':
                                                        'form-control'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':
                                                             'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':
                                                                 'form-control'
                                                                 }))


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'father_name',
                  'email', 'phone_number', 'image')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'father_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.views import PasswordChangeView
from django.db import transaction
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy

from animals_app.models import Animal
from comments_app.models import Comment
from .forms import (
    CustomUserCreationForm,
    CustomAuthenticationForm,
    UserProfileEditForm,
    CustomPasswordChangeForm
    )
from .utils import is_admin


@login_required(login_url='users:login')
def view_profile(request: HttpRequest) -> HttpResponse:
    user_animals = Animal.objects.filter(submit=request.user)
    return render(request, 'users/profile.html',
                           {'user_animals': user_animals})


@login_required(login_url='users:login')
@user_passes_test(is_admin)
def view_admin_dashboard(request: HttpRequest) -> HttpResponse:
    animals = Animal.objects.filter(is_verified=False)
    comments = Comment.objects.filter(is_verified=False)
    context = {
        'animals': animals,
        'comments': comments
    }
    return render(request, 'users/admin.html', context)


@transaction.atomic
def register_user_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('animals:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = CustomAuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('animals:index')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request: HttpRequest) -> HttpResponseRedirect:
    logout(request)
    return redirect('animals:index')


@login_required(login_url='users:login')
def edit_profile_view(request: HttpRequest) -> HttpResponse:
    user = request.user
    if request.method == 'POST':
        form = UserProfileEditForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = UserProfileEditForm(instance=user)
    return render(request, 'users/edit_profile.html', {'form': form})


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'users/change_password.html'
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('users:profile')

templates/users/admin.html
{% extends 'base.html' %}
{% load static %}
{% block lists %} Панель администратора {% endblock %} 

{% block content %}
<div class="text-center">
  <h2>Панель администратора</h2>
</div>

  <h3>Объявления</h3>
  <table class="table text-center">
    <thead>
      <tr>
        <th scope="col">Цель объявления</th>
        <th scope="col">Вид животного</th>
        <th scope="col">Кличка</th>
        <th scope="col">Номер телефона</th>
        <th scope="col">Приметы</th>
        <th scope="col">Статус</th>
      </tr>
    </thead>
    <tbody>
      {% for animal in animals %}
      <tr>
        <td>{% for target in animal.target.all %} {{ target.name }}{% endfor %}</td>
        <td>{% for kind in animal.kind.all %} {{ kind.name }}{% endfor %}</td>
        <td>{{ animal.nickname }}</td>
        <td>{{ animal.phone_number }}</td>
        <td>{{ animal.signs }}</td>
        <td><input class="form-check-input animal-switch" type="checkbox" role="switch" id="animalSwitch{{ animal.id }}"
                   data-animal-id="{{ animal.id }}" {% if animal.is_verified %}checked{% endif %}></td>        
      </tr>
      {% endfor %}
    </tbody>
  </table>

<div class="mt-5">
  <h3>Комментарии</h3>
  <table class="table text-center">
    <thead>
      <tr>
        <th scope="col">Автор</th>
        <th scope="col">Email</th>
        <th scope="col">Текст</th>
        <th scope="col">Статус</th>
      </tr>
    </thead>
    <tbody>
      {% for comment in comments %}
      <tr>
        <td>{{ comment.author }}</td>
        <td>{{ comment.email }}</td>
        <td>{{ comment.text }}</td>
        <td>
          <input class="form-check-input comment-switch" type="checkbox" role="switch" id="commentSwitch{{ comment.id }}"
                 data-comment-id="{{ comment.id }}" {% if comment.is_verified %}checked{% endif %}>
        </td>         
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %} 

templates/users/change_password.html
{% extends 'base.html' %}
{% block lists %} Смена пароля {% endblock %}

{% block content %}
<div class="container mt-3">
    <h3>Смена пароля</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сменить пароль</button>
        <a href="{% url 'users:profile' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

templates/users/edit_profile.html
{% extends 'base.html' %}
{% block lists %} Редактирование профиля {% endblock %}

{% block content %}
<div class="container mt-3">
    <h3>Редактирование профиля</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'users:profile' %}" class="btn btn-secondary">Отменить</a>
    </form>
</div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block lists %}
  Вход
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-self-center">
  <div class="" style="width: 50%">
    <h1 class="h3 mb-3 fw-normal">Введите данные для входа</h1>
    <form method='POST'>
      {% csrf_token %}
      <div class="form-group">
        <label for="{{form.username.id_for_label}}">Имя пользователя</label>
        {{ form.username }}
        {% if form.username.errors %}
        <div class="text-danger">
          {{ form.username.errors }}
        </div>
        {% endif %}
      </div>
      
      <div class="form-group">
        <label for="{{form.password.id_for_label}}">Пароль</label>
        {{ form.password }}
        {% if form.password.errors %}
        <div class="text-danger">
          {{ form.password.errors }}
        </div>
        {% endif %}
      </div>
      
      <button class="btn btn-primary mt-3" type="submit">Войти</button>
      {% if form.non_field_errors %}
      <div class="alert alert-danger mt-5 2" style="width: 100%">
        {{ form.non_field_errors }}
      </div>
      {% endif %}
    </form>
  </div>
</div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block lists %}
  Страница профиля
{% endblock %}

{% block content %}
<div>
    <div class="d-flex justify-content-around mt-3">
        <div class="text-center">
            <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/default_img.jpg'%} {% endif %}" class="rounded" style="width: 420px;">
        </div>
        <div>
            <h4>{{ user.last_name }}</h4>
            <h4>{{ user.first_name }}</h4>
            <h4>{{ user.father_name }}</h4>
            <p><h4>Email: {{ user.email }}</p></h4>
            <p><h4>Номер телефона: {{ user.phone_number }}</p></h4>
            <div class="btn-group" role="group">
                <a href="{% url 'users:edit_profile' %}" class="btn btn-info">Изменить данные</a>
                <a href="{% url 'users:change_password' %}" class="btn btn-warning">Изменить пароль</a>
              </div>
        </div>
    </div>
    
    <div class="mt-4">
        <h3>Ваши объявления</h3>
        <table class="table text-center mt-3">
            <thead>
                <tr>
                    <th scope="col">Цель объявления</th>
                    <th scope="col">Вид животного</th>
                    <th scope="col">Дата подачи</th>
                    <th scope="col">Описание</th>
                    <th scope="col">Подающий объявление</th>
                    <th scope="col">Действие</th>
                </tr>
            </thead>
            <tbody>
            {% for animal in user_animals %}
            <tr>
                <td>{% for target in animal.target.all %} {{ target.name }}{% endfor %}</td>
                <td>{% for kind in animal.kind.all %} {{ kind.name }}{% endfor %}</td>
                <td>{{ animal.create_at }}</td>
                <td>{{ animal.description }}</td>
                <td>{{ animal.submit }}</td>
                <td>
                    <div class="btn-group" role="group">
                        <a href="{% url 'animals:delete_animal' animal.id %}" class="btn btn-danger">Удалить</a>
                        <a href="{% url 'animals:edit_animal' animal.id %}" class="btn btn-warning">Изменить</a>
                      </div>
                </td>
            </tr>            
            {% endfor %}
            </tbody>
          </table>
    </div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% block lists %}
  Регистрация пользователя
{% endblock %}

{% block content %}
  <div class="d-flex justify-content-center align-self-center">
    <div class="" style="width: 50%">
        <h2>Регистрация</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </form>
    </div>
  </div>
{% endblock %}